# colorscheme(hybrid)
[[plugins]]
repo = 'w0ng/vim-hybrid'

# comment out
[[plugins]]
repo = 'tpope/vim-commentary'

# directory tree
[[plugins]]
repo = 'scrooloose/nerdtree'

# filetype icons
[[plugins]]
repo = 'ryanoasis/vim-devicons'

# status bar
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# line status @git
[[plugins]]
repo = 'airblade/vim-gitgutter'

# nerdtree add git status
[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

# use git @vim
[[plugins]]
repo = 'tpope/vim-fugitive'

# auto close tag
[[plugins]]
repo = 'alvan/vim-closetag'
hook_add = '''
  let g:closetag_filetypes = 'html,php'
'''

# highlight whitespace
[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

# dark powered complete tool
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 200
  let g:deoplete#auto_complete_start_length = 2
'''
# required for vim8
[[plugins]]
repo = 'roxma/nvim-yarp'
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

# snippet
[[plugins]]
repo = 'Shougo/neosnippet.vim'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_source = ['neosnippet.vim']

# show colors
[[plugins]]
repo = 'ap/vim-css-color'

# show indent
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_char = '¦'
'''

# auto close pare
[[plugins]]
repo = 'cohama/lexima.vim'
hook_add = '''
  let g:lexima_ctrlh_as_backspace = 1
'''

# auto save
[[plugins]]
repo = 'vim-scripts/vim-auto-save'
hook_add = '''
  let g:auto_save_no_updatetime = 1
  let g:auto_save_in_insert_mode = 0
'''

# vim surround
[[plugins]]
repo = 'tpope/vim-surround'

# plugin repeat for the .
[[plugins]]
repo = 'tpope/vim-repeat'

# interface for vim (Dark powered unite.vim)
[[plugins]]
repo = 'Shougo/denite.nvim'

# phpactor
[[plugins]]
repo = 'phpactor/phpactor'
build = 'composer install'
# for deoplete
[[plugins]]
repo = 'kristijanhusak/deoplete-phpactor'

# vim language-packs
[[plugins]]
repo = 'sheerun/vim-polyglot'
